#pragma once
//
// Declarations for the function bodies recovered in ps2xRuntime/src/lib/Kernel/recovered/.
//
// WHY THESE EXIST
// ---------------
// export_func_map.py built sdbz_func_map_merged.csv by walking idautils.Functions()
// and writing f.start_ea/f.end_ea. In IDA's model a function is a set of CHUNKS, and
// those two fields describe only the ENTRY chunk -- every tail chunk was silently
// dropped from the map. The recompiler emits one body per map row, so the dropped
// ranges got no body, and a direct `j` into one dispatched to nothing. That is the
// "missing-body" dispatch-hole class.
//
// The map now carries those ranges (build_scripts/funcmap/recover_hole_boundaries.py),
// and these are the bodies the production recompiler emitted for them -- machine
// translation, not hand-decoded MIPS.
//
// WHY THEY LIVE HERE AND NOT IN runner/
// -------------------------------------
// build.ps1 regenerates fn_forward_decls.h from a scan of the runner directory, and
// that header is included by all ~4,520 runner TUs. Adding files to runner/ would
// rewrite it and trigger a 30+ hour full rebuild. ps2xRuntime/CMakeLists.txt already
// does GLOB_RECURSE over src/lib/Kernel/*.cpp with CONFIGURE_DEPENDS, so this
// subfolder is picked up with no CMakeLists edit and no runner rebuild.
//
// This header is included ONLY by game_overrides.cpp, which registers these bodies.
// Do not include it from a widely-included header.
//
// GENERATED by build_scripts/funcmap/gen_recovered_header.py -- do not hand-edit.

#include <cstdint>

struct R5900Context;
class PS2Runtime;

void sub_199240_tail00103F30_0x103f30(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00115348_0x115348(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001153C8_0x1153c8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00117248_0x117248(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00117498_0x117498(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001174F8_0x1174f8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00117558_0x117558(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00117580_0x117580(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00117588_0x117588(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00117590_0x117590(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001175A8_0x1175a8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001175B0_0x1175b0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00117710_0x117710(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00117730_0x117730(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00117978_0x117978(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00119B70_0x119b70(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00119F38_0x119f38(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00121CC8_0x121cc8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00121DC8_0x121dc8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00122108_0x122108(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001242C8_0x1242c8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0012BFB0_0x12bfb0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0012C0A8_0x12c0a8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0012EA80_0x12ea80(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0012EA90_0x12ea90(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0012EAA0_0x12eaa0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0012EAB0_0x12eab0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0012EB18_0x12eb18(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_132430_tail0012F750_0x12f750(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001314B0_0x1314b0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001314D0_0x1314d0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001314F0_0x1314f0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00137590_0x137590(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001375E0_0x1375e0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00137628_0x137628(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00137630_0x137630(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00137888_0x137888(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00138018_0x138018(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00138110_0x138110(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001384C0_0x1384c0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00138568_0x138568(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001385A8_0x1385a8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001385F8_0x1385f8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001386C0_0x1386c0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001386F0_0x1386f0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00138720_0x138720(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00138758_0x138758(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00138788_0x138788(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00138A28_0x138a28(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0013AF20_0x13af20(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0013C8E8_0x13c8e8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0013C940_0x13c940(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0013CA18_0x13ca18(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_14A840_tail0014A890_0x14a890(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0014D010_0x14d010(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0014E330_0x14e330(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001505F0_0x1505f0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00155808_0x155808(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001581B8_0x1581b8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001582D8_0x1582d8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001590F0_0x1590f0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0015B7D8_0x15b7d8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0015B7F0_0x15b7f0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0015BB78_0x15bb78(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0015E460_0x15e460(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00167D08_0x167d08(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016B368_0x16b368(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016B398_0x16b398(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016B580_0x16b580(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016C888_0x16c888(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016C898_0x16c898(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016E0D0_0x16e0d0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016E0F0_0x16e0f0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016E128_0x16e128(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016E780_0x16e780(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016E788_0x16e788(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016E798_0x16e798(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016E7A8_0x16e7a8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016E7B8_0x16e7b8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F008_0x16f008(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F308_0x16f308(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F328_0x16f328(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F348_0x16f348(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F360_0x16f360(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F3B8_0x16f3b8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F4A0_0x16f4a0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F4A8_0x16f4a8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F4B0_0x16f4b0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F4B8_0x16f4b8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F598_0x16f598(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F5A0_0x16f5a0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F5A8_0x16f5a8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F5B0_0x16f5b0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F5B8_0x16f5b8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0016F678_0x16f678(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00170110_0x170110(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00170158_0x170158(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001706E0_0x1706e0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00173F90_0x173f90(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001750C0_0x1750c0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00182820_0x182820(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_186068_tail00182878_0x182878(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_186068_tail00182940_0x182940(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_186068_tail00182AB0_0x182ab0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_186068_tail00182AC8_0x182ac8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_1DBDB0_tail001CD4F0_0x1cd4f0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_1DBE00_tail001CD5E0_0x1cd5e0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_290A50_tail002A6640_0x2a6640(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_290A70_tail002A6770_0x2a6770(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_2B0530_tail002ADD50_0x2add50(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_2B1310_tail002B6880_0x2b6880(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_2E1B80_tail002E3910_0x2e3910(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_2E1B40_tail002E3920_0x2e3920(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_2F8180_tail002E5010_0x2e5010(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_1F5950_tail002FCD10_0x2fcd10(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_309F10_tail00305DE0_0x305de0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_309F30_tail00305DF0_0x305df0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_309FE0_tail00305E00_0x305e00(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_30A000_tail00305E10_0x305e10(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_309F90_tail00307100_0x307100(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_30A020_tail00307A40_0x307a40(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_30A050_tail00307F80_0x307f80(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_30A320_tail00308600_0x308600(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_40B130_tail00343480_0x343480(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_370C80_tail003704B0_0x3704b0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_3793D0_tail00377DA0_0x377da0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_37AA50_tail00379390_0x379390(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_398E10_tail00397C50_0x397c50(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_3A2B60_tail003A26E0_0x3a26e0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_3A2B70_tail003A2700_0x3a2700(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_3A32F0_tail003A2ED0_0x3a2ed0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00425028_0x425028(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00425118_0x425118(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00428190_0x428190(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0042A0E8_0x42a0e8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);

// Guest address -> recovered body. Addresses already claimed by a hand-written
// override (registerFunction or replaceFunction in game_overrides.cpp) are
// deliberately absent: the working override must keep the address.
struct RecoveredFn
{
    uint32_t addr;
    void (*fn)(uint8_t *, R5900Context *, PS2Runtime *);
};

inline constexpr RecoveredFn kRecoveredFns[] = {
    {0x00103F30u, &sub_199240_tail00103F30_0x103f30},
    {0x00115348u, &sub_00115348_0x115348},
    {0x001153C8u, &sub_001153C8_0x1153c8},
    {0x00117248u, &sub_00117248_0x117248},
    {0x00117498u, &sub_00117498_0x117498},
    {0x001174F8u, &sub_001174F8_0x1174f8},
    {0x00117558u, &sub_00117558_0x117558},
    {0x00117580u, &sub_00117580_0x117580},
    {0x00117588u, &sub_00117588_0x117588},
    {0x00117590u, &sub_00117590_0x117590},
    {0x001175A8u, &sub_001175A8_0x1175a8},
    {0x001175B0u, &sub_001175B0_0x1175b0},
    {0x00117710u, &sub_00117710_0x117710},
    {0x00117730u, &sub_00117730_0x117730},
    {0x00117978u, &sub_00117978_0x117978},
    {0x00119B70u, &sub_00119B70_0x119b70},
    {0x00119F38u, &sub_00119F38_0x119f38},
    {0x00121CC8u, &sub_00121CC8_0x121cc8},
    {0x00121DC8u, &sub_00121DC8_0x121dc8},
    {0x00122108u, &sub_00122108_0x122108},
    {0x001242C8u, &sub_001242C8_0x1242c8},
    {0x0012BFB0u, &sub_0012BFB0_0x12bfb0},
    {0x0012C0A8u, &sub_0012C0A8_0x12c0a8},
    {0x0012EA80u, &sub_0012EA80_0x12ea80},
    {0x0012EA90u, &sub_0012EA90_0x12ea90},
    {0x0012EAA0u, &sub_0012EAA0_0x12eaa0},
    {0x0012EAB0u, &sub_0012EAB0_0x12eab0},
    {0x0012EB18u, &sub_0012EB18_0x12eb18},
    {0x0012F750u, &sub_132430_tail0012F750_0x12f750},
    {0x001314B0u, &sub_001314B0_0x1314b0},
    {0x001314D0u, &sub_001314D0_0x1314d0},
    {0x001314F0u, &sub_001314F0_0x1314f0},
    {0x00137590u, &sub_00137590_0x137590},
    {0x001375E0u, &sub_001375E0_0x1375e0},
    {0x00137628u, &sub_00137628_0x137628},
    {0x00137630u, &sub_00137630_0x137630},
    {0x00137888u, &sub_00137888_0x137888},
    {0x00138018u, &sub_00138018_0x138018},
    {0x00138110u, &sub_00138110_0x138110},
    {0x001384C0u, &sub_001384C0_0x1384c0},
    {0x00138568u, &sub_00138568_0x138568},
    {0x001385A8u, &sub_001385A8_0x1385a8},
    {0x001385F8u, &sub_001385F8_0x1385f8},
    {0x001386C0u, &sub_001386C0_0x1386c0},
    {0x001386F0u, &sub_001386F0_0x1386f0},
    {0x00138720u, &sub_00138720_0x138720},
    {0x00138758u, &sub_00138758_0x138758},
    {0x00138788u, &sub_00138788_0x138788},
    {0x00138A28u, &sub_00138A28_0x138a28},
    {0x0013AF20u, &sub_0013AF20_0x13af20},
    {0x0013C8E8u, &sub_0013C8E8_0x13c8e8},
    {0x0013C940u, &sub_0013C940_0x13c940},
    {0x0013CA18u, &sub_0013CA18_0x13ca18},
    {0x0014A890u, &sub_14A840_tail0014A890_0x14a890},
    {0x0014D010u, &sub_0014D010_0x14d010},
    {0x0014E330u, &sub_0014E330_0x14e330},
    {0x001505F0u, &sub_001505F0_0x1505f0},
    {0x00155808u, &sub_00155808_0x155808},
    {0x001581B8u, &sub_001581B8_0x1581b8},
    {0x001582D8u, &sub_001582D8_0x1582d8},
    {0x001590F0u, &sub_001590F0_0x1590f0},
    {0x0015B7D8u, &sub_0015B7D8_0x15b7d8},
    {0x0015B7F0u, &sub_0015B7F0_0x15b7f0},
    {0x0015BB78u, &sub_0015BB78_0x15bb78},
    {0x0015E460u, &sub_0015E460_0x15e460},
    {0x00167D08u, &sub_00167D08_0x167d08},
    {0x0016B368u, &sub_0016B368_0x16b368},
    {0x0016B398u, &sub_0016B398_0x16b398},
    {0x0016B580u, &sub_0016B580_0x16b580},
    {0x0016C888u, &sub_0016C888_0x16c888},
    {0x0016C898u, &sub_0016C898_0x16c898},
    {0x0016E0D0u, &sub_0016E0D0_0x16e0d0},
    {0x0016E0F0u, &sub_0016E0F0_0x16e0f0},
    {0x0016E128u, &sub_0016E128_0x16e128},
    {0x0016E780u, &sub_0016E780_0x16e780},
    {0x0016E788u, &sub_0016E788_0x16e788},
    {0x0016E798u, &sub_0016E798_0x16e798},
    {0x0016E7A8u, &sub_0016E7A8_0x16e7a8},
    {0x0016E7B8u, &sub_0016E7B8_0x16e7b8},
    {0x0016F008u, &sub_0016F008_0x16f008},
    {0x0016F308u, &sub_0016F308_0x16f308},
    {0x0016F328u, &sub_0016F328_0x16f328},
    {0x0016F348u, &sub_0016F348_0x16f348},
    {0x0016F360u, &sub_0016F360_0x16f360},
    {0x0016F3B8u, &sub_0016F3B8_0x16f3b8},
    {0x0016F4A0u, &sub_0016F4A0_0x16f4a0},
    {0x0016F4A8u, &sub_0016F4A8_0x16f4a8},
    {0x0016F4B0u, &sub_0016F4B0_0x16f4b0},
    {0x0016F4B8u, &sub_0016F4B8_0x16f4b8},
    {0x0016F598u, &sub_0016F598_0x16f598},
    {0x0016F5A0u, &sub_0016F5A0_0x16f5a0},
    {0x0016F5A8u, &sub_0016F5A8_0x16f5a8},
    {0x0016F5B0u, &sub_0016F5B0_0x16f5b0},
    {0x0016F5B8u, &sub_0016F5B8_0x16f5b8},
    {0x0016F678u, &sub_0016F678_0x16f678},
    {0x00170110u, &sub_00170110_0x170110},
    {0x00170158u, &sub_00170158_0x170158},
    {0x001706E0u, &sub_001706E0_0x1706e0},
    {0x00173F90u, &sub_00173F90_0x173f90},
    {0x001750C0u, &sub_001750C0_0x1750c0},
    {0x00182820u, &sub_00182820_0x182820},
    {0x00182878u, &sub_186068_tail00182878_0x182878},
    {0x00182940u, &sub_186068_tail00182940_0x182940},
    {0x00182AB0u, &sub_186068_tail00182AB0_0x182ab0},
    {0x00182AC8u, &sub_186068_tail00182AC8_0x182ac8},
    {0x001CD4F0u, &sub_1DBDB0_tail001CD4F0_0x1cd4f0},
    {0x001CD5E0u, &sub_1DBE00_tail001CD5E0_0x1cd5e0},
    {0x002A6640u, &sub_290A50_tail002A6640_0x2a6640},
    {0x002A6770u, &sub_290A70_tail002A6770_0x2a6770},
    {0x002ADD50u, &sub_2B0530_tail002ADD50_0x2add50},
    {0x002B6880u, &sub_2B1310_tail002B6880_0x2b6880},
    {0x002E3910u, &sub_2E1B80_tail002E3910_0x2e3910},
    {0x002E3920u, &sub_2E1B40_tail002E3920_0x2e3920},
    {0x002E5010u, &sub_2F8180_tail002E5010_0x2e5010},
    {0x002FCD10u, &sub_1F5950_tail002FCD10_0x2fcd10},
    {0x00305DE0u, &sub_309F10_tail00305DE0_0x305de0},
    {0x00305DF0u, &sub_309F30_tail00305DF0_0x305df0},
    {0x00305E00u, &sub_309FE0_tail00305E00_0x305e00},
    {0x00305E10u, &sub_30A000_tail00305E10_0x305e10},
    {0x00307100u, &sub_309F90_tail00307100_0x307100},
    {0x00307A40u, &sub_30A020_tail00307A40_0x307a40},
    {0x00307F80u, &sub_30A050_tail00307F80_0x307f80},
    {0x00308600u, &sub_30A320_tail00308600_0x308600},
    {0x00343480u, &sub_40B130_tail00343480_0x343480},
    {0x003704B0u, &sub_370C80_tail003704B0_0x3704b0},
    {0x00377DA0u, &sub_3793D0_tail00377DA0_0x377da0},
    {0x00379390u, &sub_37AA50_tail00379390_0x379390},
    {0x00397C50u, &sub_398E10_tail00397C50_0x397c50},
    {0x003A26E0u, &sub_3A2B60_tail003A26E0_0x3a26e0},
    {0x003A2700u, &sub_3A2B70_tail003A2700_0x3a2700},
    {0x003A2ED0u, &sub_3A32F0_tail003A2ED0_0x3a2ed0},
    {0x00425028u, &sub_00425028_0x425028},
    {0x00425118u, &sub_00425118_0x425118},
    {0x00428190u, &sub_00428190_0x428190},
    {0x0042A0E8u, &sub_0042A0E8_0x42a0e8},
};
