#pragma once
//
// Declarations for the function bodies recovered in ps2xRuntime/src/lib/Kernel/recovered/.
//
// WHY THESE EXIST
// ---------------
// export_func_map.py built sdbz_func_map_merged.csv by walking idautils.Functions()
// and writing f.start_ea/f.end_ea. In IDA's model a function is a set of CHUNKS, and
// those two fields describe only the ENTRY chunk -- every tail chunk was silently
// dropped from the map. The recompiler emits one body per map row, so the dropped
// ranges got no body, and a direct `j` into one dispatched to nothing. That is the
// "missing-body" dispatch-hole class.
//
// The map now carries those ranges (build_scripts/funcmap/recover_hole_boundaries.py),
// and these are the bodies the production recompiler emitted for them -- machine
// translation, not hand-decoded MIPS.
//
// WHY THEY LIVE HERE AND NOT IN runner/
// -------------------------------------
// build.ps1 regenerates fn_forward_decls.h from a scan of the runner directory, and
// that header is included by all ~4,520 runner TUs. Adding files to runner/ would
// rewrite it and trigger a 30+ hour full rebuild. ps2xRuntime/CMakeLists.txt already
// does GLOB_RECURSE over src/lib/Kernel/*.cpp with CONFIGURE_DEPENDS, so this
// subfolder is picked up with no CMakeLists edit and no runner rebuild.
//
// This header is included ONLY by game_overrides.cpp, which registers these bodies.
// Do not include it from a widely-included header.
//
// GENERATED by build_scripts/funcmap/gen_recovered_header.py -- do not hand-edit.

#include <cstdint>

struct R5900Context;
class PS2Runtime;

void sub_00119B70_0x119b70(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00119F38_0x119f38(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00130348_0x130348(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001581B8_0x1581b8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00173F90_0x173f90(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001750C0_0x1750c0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00177AA8_0x177aa8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00178B58_0x178b58(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0019C5D0_0x19c5d0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001AC6F0_0x1ac6f0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001AD0B0_0x1ad0b0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001AD5A0_0x1ad5a0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001AD6A0_0x1ad6a0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001AD700_0x1ad700(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001AD760_0x1ad760(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001BA820_0x1ba820(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001BB750_0x1bb750(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001BC2A0_0x1bc2a0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001BC4E0_0x1bc4e0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001BF270_0x1bf270(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001C0040_0x1c0040(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001C97F0_0x1c97f0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001CAF20_0x1caf20(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001D2490_0x1d2490(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001D2D80_0x1d2d80(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001D30D0_0x1d30d0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001D4F00_0x1d4f00(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001D6BB0_0x1d6bb0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001D83C0_0x1d83c0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001D93F0_0x1d93f0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001D9790_0x1d9790(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001D9BC0_0x1d9bc0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001DA1B0_0x1da1b0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001E5650_0x1e5650(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001EB910_0x1eb910(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001ECF80_0x1ecf80(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001EFA00_0x1efa00(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001F01D0_0x1f01d0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001F0540_0x1f0540(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001F5560_0x1f5560(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001F56F0_0x1f56f0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001F5C90_0x1f5c90(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_001F5ED0_0x1f5ed0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0022C6D0_0x22c6d0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0022CA60_0x22ca60(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0022CDC0_0x22cdc0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0023B3C0_0x23b3c0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0023C0E0_0x23c0e0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0023C2E0_0x23c2e0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0023C3D0_0x23c3d0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0023D840_0x23d840(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0023E280_0x23e280(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0023E490_0x23e490(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0023E530_0x23e530(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_002407B0_0x2407b0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00240980_0x240980(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00240B10_0x240b10(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00241C90_0x241c90(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00241CB0_0x241cb0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_002972F0_0x2972f0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_2B1310_tail002B6880_0x2b6880(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_002B8AC0_0x2b8ac0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_002B94C0_0x2b94c0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_002CA200_0x2ca200(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_002CF080_0x2cf080(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_002E3DA0_0x2e3da0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_002E3F40_0x2e3f40(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_2F8180_tail002E5010_0x2e5010(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_002F4430_0x2f4430(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_002F4690_0x2f4690(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_002F4E10_0x2f4e10(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00300690_0x300690(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0032B8C0_0x32b8c0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0038AF90_0x38af90(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0038D920_0x38d920(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0038DAC0_0x38dac0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0038DBC0_0x38dbc0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0038DCC0_0x38dcc0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_003A24D0_0x3a24d0(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_003A2D00_0x3a2d00(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_003D0770_0x3d0770(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00425028_0x425028(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_00425118_0x425118(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);
void sub_0042A0E8_0x42a0e8(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);

// Guest address -> recovered body. Addresses already claimed by a hand-written
// override (registerFunction or replaceFunction in game_overrides.cpp) are
// deliberately absent: the working override must keep the address.
//
// `end` (exclusive) comes from the body's own "// Address: start - end" line.
// The generated table maps EVERY instruction of a body to that body, and the EE
// scheduler resumes a thread by looking up its saved pc -- so registering only
// the entry leaves a thread that yields inside a recovered body resuming into a
// hole (2026-09-14: 0x1aca90 inside sub_001AC6F0 froze the game at t=1451).
struct RecoveredFn
{
    uint32_t addr;
    uint32_t end;
    void (*fn)(uint8_t *, R5900Context *, PS2Runtime *);
};

inline constexpr RecoveredFn kRecoveredFns[] = {
    {0x00119B70u, 0x00119F38u, &sub_00119B70_0x119b70},
    {0x00119F38u, 0x0011A280u, &sub_00119F38_0x119f38},
    {0x00130348u, 0x00130360u, &sub_00130348_0x130348},
    {0x001581B8u, 0x001581E8u, &sub_001581B8_0x1581b8},
    {0x00173F90u, 0x00174038u, &sub_00173F90_0x173f90},
    {0x001750C0u, 0x001750D0u, &sub_001750C0_0x1750c0},
    {0x00177AA8u, 0x00177AB8u, &sub_00177AA8_0x177aa8},
    {0x00178B58u, 0x00178BE8u, &sub_00178B58_0x178b58},
    {0x0019C5D0u, 0x0019C5F0u, &sub_0019C5D0_0x19c5d0},
    {0x001AC6F0u, 0x001AD0B0u, &sub_001AC6F0_0x1ac6f0},
    {0x001AD0B0u, 0x001AD5A0u, &sub_001AD0B0_0x1ad0b0},
    {0x001AD5A0u, 0x001AD6A0u, &sub_001AD5A0_0x1ad5a0},
    {0x001AD6A0u, 0x001AD700u, &sub_001AD6A0_0x1ad6a0},
    {0x001AD700u, 0x001AD760u, &sub_001AD700_0x1ad700},
    {0x001AD760u, 0x001AD7B0u, &sub_001AD760_0x1ad760},
    {0x001BA820u, 0x001BA850u, &sub_001BA820_0x1ba820},
    {0x001BB750u, 0x001BB780u, &sub_001BB750_0x1bb750},
    {0x001BC2A0u, 0x001BC340u, &sub_001BC2A0_0x1bc2a0},
    {0x001BC4E0u, 0x001BC510u, &sub_001BC4E0_0x1bc4e0},
    {0x001BF270u, 0x001BF2E0u, &sub_001BF270_0x1bf270},
    {0x001C0040u, 0x001C0060u, &sub_001C0040_0x1c0040},
    {0x001C97F0u, 0x001C9810u, &sub_001C97F0_0x1c97f0},
    {0x001CAF20u, 0x001CAF40u, &sub_001CAF20_0x1caf20},
    {0x001D2490u, 0x001D24B0u, &sub_001D2490_0x1d2490},
    {0x001D2D80u, 0x001D2DA0u, &sub_001D2D80_0x1d2d80},
    {0x001D30D0u, 0x001D30F0u, &sub_001D30D0_0x1d30d0},
    {0x001D4F00u, 0x001D4F20u, &sub_001D4F00_0x1d4f00},
    {0x001D6BB0u, 0x001D6BD0u, &sub_001D6BB0_0x1d6bb0},
    {0x001D83C0u, 0x001D83E0u, &sub_001D83C0_0x1d83c0},
    {0x001D93F0u, 0x001D9410u, &sub_001D93F0_0x1d93f0},
    {0x001D9790u, 0x001D97B0u, &sub_001D9790_0x1d9790},
    {0x001D9BC0u, 0x001D9BE0u, &sub_001D9BC0_0x1d9bc0},
    {0x001DA1B0u, 0x001DA1D0u, &sub_001DA1B0_0x1da1b0},
    {0x001E5650u, 0x001E5670u, &sub_001E5650_0x1e5650},
    {0x001EB910u, 0x001EB930u, &sub_001EB910_0x1eb910},
    {0x001ECF80u, 0x001ECFA0u, &sub_001ECF80_0x1ecf80},
    {0x001EFA00u, 0x001EFA20u, &sub_001EFA00_0x1efa00},
    {0x001F01D0u, 0x001F01F0u, &sub_001F01D0_0x1f01d0},
    {0x001F0540u, 0x001F0560u, &sub_001F0540_0x1f0540},
    {0x001F5560u, 0x001F5580u, &sub_001F5560_0x1f5560},
    {0x001F56F0u, 0x001F5710u, &sub_001F56F0_0x1f56f0},
    {0x001F5C90u, 0x001F5CB0u, &sub_001F5C90_0x1f5c90},
    {0x001F5ED0u, 0x001F5F10u, &sub_001F5ED0_0x1f5ed0},
    {0x0022C6D0u, 0x0022C6F0u, &sub_0022C6D0_0x22c6d0},
    {0x0022CA60u, 0x0022CA80u, &sub_0022CA60_0x22ca60},
    {0x0022CDC0u, 0x0022CDE0u, &sub_0022CDC0_0x22cdc0},
    {0x0023B3C0u, 0x0023B3E0u, &sub_0023B3C0_0x23b3c0},
    {0x0023C0E0u, 0x0023C100u, &sub_0023C0E0_0x23c0e0},
    {0x0023C2E0u, 0x0023C300u, &sub_0023C2E0_0x23c2e0},
    {0x0023C3D0u, 0x0023C450u, &sub_0023C3D0_0x23c3d0},
    {0x0023D840u, 0x0023D860u, &sub_0023D840_0x23d840},
    {0x0023E280u, 0x0023E2A0u, &sub_0023E280_0x23e280},
    {0x0023E490u, 0x0023E4B0u, &sub_0023E490_0x23e490},
    {0x0023E530u, 0x0023E550u, &sub_0023E530_0x23e530},
    {0x002407B0u, 0x002407D0u, &sub_002407B0_0x2407b0},
    {0x00240980u, 0x002409A0u, &sub_00240980_0x240980},
    {0x00240B10u, 0x00240B30u, &sub_00240B10_0x240b10},
    {0x00241C90u, 0x00241CD0u, &sub_00241C90_0x241c90},
    {0x00241CB0u, 0x00241CCCu, &sub_00241CB0_0x241cb0},
    {0x002972F0u, 0x00297310u, &sub_002972F0_0x2972f0},
    {0x002B6880u, 0x002B6900u, &sub_2B1310_tail002B6880_0x2b6880},
    {0x002B8AC0u, 0x002B8ADCu, &sub_002B8AC0_0x2b8ac0},
    {0x002B94C0u, 0x002B94E0u, &sub_002B94C0_0x2b94c0},
    {0x002CA200u, 0x002CA220u, &sub_002CA200_0x2ca200},
    {0x002CF080u, 0x002CF0A0u, &sub_002CF080_0x2cf080},
    {0x002E3DA0u, 0x002E3E60u, &sub_002E3DA0_0x2e3da0},
    {0x002E3F40u, 0x002E3F60u, &sub_002E3F40_0x2e3f40},
    {0x002E5010u, 0x002E5040u, &sub_2F8180_tail002E5010_0x2e5010},
    {0x002F4430u, 0x002F4450u, &sub_002F4430_0x2f4430},
    {0x002F4690u, 0x002F46B0u, &sub_002F4690_0x2f4690},
    {0x002F4E10u, 0x002F4E70u, &sub_002F4E10_0x2f4e10},
    {0x00300690u, 0x003006B0u, &sub_00300690_0x300690},
    {0x0032B8C0u, 0x0032B8E0u, &sub_0032B8C0_0x32b8c0},
    {0x0038AF90u, 0x0038B030u, &sub_0038AF90_0x38af90},
    {0x0038D920u, 0x0038D940u, &sub_0038D920_0x38d920},
    {0x0038DAC0u, 0x0038DAE0u, &sub_0038DAC0_0x38dac0},
    {0x0038DBC0u, 0x0038DBE0u, &sub_0038DBC0_0x38dbc0},
    {0x0038DCC0u, 0x0038DCE0u, &sub_0038DCC0_0x38dcc0},
    {0x003A24D0u, 0x003A24F0u, &sub_003A24D0_0x3a24d0},
    {0x003A2D00u, 0x003A2D20u, &sub_003A2D00_0x3a2d00},
    {0x003D0770u, 0x003D0790u, &sub_003D0770_0x3d0770},
    {0x00425028u, 0x00425118u, &sub_00425028_0x425028},
    {0x00425118u, 0x004251D8u, &sub_00425118_0x425118},
    {0x0042A0E8u, 0x0042A150u, &sub_0042A0E8_0x42a0e8},
};
