#!/usr/bin/env python3
"""gen_sqrt_abs_overrides.py -- PS2 square roots of negative operands, for EVERY generated function.

The R5900 (and PCSX2) take sqrt(|x|) for a negative operand; our translations do not
(opcode conformance test 10-08):
  sqrt.s          FPU_SQRT_S (ps2_runtime_macros.h) returns NaN 0xFFC00000
  vsqrt  (VU0)    Q = sqrtf(std::max(0.0f, ft))            -> 0
  vrsqrt (VU0)    Q = (ft > 0) ? 1/sqrtf(ft) : 0           -> 0, ignores fs, 0 for ft == 0
Fixing them is a header or recompiler change (every runner TU rebuilds, 30+ h), so instead
every runner function containing one gets an override: its own generated body, renamed
sdbzSqrtAbs_<name>, with only those expressions rewritten (fix_source). Nothing else changes.
game_overrides.cpp registers each copy over every word of its range (table .inc below).
gen_conformance.py --game-fixes applies the same fix_source to the conformance test functions,
so the rewrite is checked against PCSX2 offline (conformance.ps1 -GameFixes).

Writes (game-derived, gitignored):
  ps2xRuntime/src/lib/Kernel/FpuFixes/sqrt_abs_overrides*.cpp
  ps2xRuntime/src/lib/Kernel/FpuFixes/sqrt_abs_overrides_table.inc

    python build_scripts/conformance/gen_sqrt_abs_overrides.py          (check + write)
    python build_scripts/conformance/gen_sqrt_abs_overrides.py --check  (report only)
"""
import argparse
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "output"                       # production recompiler output (09-26)
RUNNER = ROOT / "ps2xRuntime" / "src" / "runner"
FIXDIR = ROOT / "ps2xRuntime" / "src" / "lib" / "Kernel" / "FpuFixes"
OVERRIDES = ROOT / "ps2xRuntime" / "src" / "lib" / "game_overrides.cpp"
RECOVERED_H = ROOT / "ps2xRuntime" / "src" / "lib" / "Kernel" / "recovered" / "recovered_functions.h"
FUNC_MAP = ROOT / "build_scripts" / "funcmap" / "sdbz_func_map_regen.csv"
PREFIX = "sdbzSqrtAbs_"
CHUNK_BYTES = 1_000_000

HEADER = """// GENERATED by build_scripts/conformance/gen_sqrt_abs_overrides.py -- do not edit; re-run it.
//
// Square roots of negative operands. The R5900 (and PCSX2) take sqrt(|x|):
//   sqrt.s  : FPU_SQRT_S in ps2_runtime_macros.h returns the x86 default NaN 0xFFC00000
//             (PCSX2 iFPU.cpp recSQRT_S_xmm ANDs the sign bit off before sqrtss). The first
//             three sites (10-04) made Krillin's NaN bone matrices.
//   vsqrt   : our Q = sqrtf(max(0, ft)) = 0; PCSX2 VUops.cpp _vuSQRT: Q = sqrt(|ft|).
//   vrsqrt  : our Q = ft > 0 ? 1/sqrtf(ft) : 0 (fs ignored); PCSX2 _vuRSQRT: Q = fs/sqrt(|ft|),
//             ft == 0 -> +-FLT_MAX (fs != 0) or +-0 (fs == 0), sign = sign(fs) ^ sign(ft).
// Fixing them is a header / recompiler change (every runner TU rebuilds), so every runner
// function containing one is overridden instead (opcode conformance test 10-08: all three
// FAIL on every negative input). VU STATUS flags are not modelled (no VU0 macro op sets them).
//
// Each body is the production recompiler's output for its address, byte-identical
// to output/<name>.cpp (checked against runner/<name>.cpp), renamed with an
// sdbzSqrtAbs_ prefix, with only those expressions rewritten (gen_sqrt_abs_overrides.py
// fix_source). Nothing else changed. Registered over the runner slots (entry + every interior word) from
// game_overrides.cpp via sqrt_abs_overrides_table.inc; dispatchGuestBranch resolves
// every jal/jalr through the table, so all callers reach these.
#include <cmath>
#include <cstring>
#include <stdexcept>
#include "ps2_runtime_macros.h"
#include "ps2_runtime.h"
#include "ps2_recompiled_functions.h"
#include "ps2_recompiled_stubs.h"

#include "ps2_syscalls.h"
#include "ps2_stubs.h"

#ifdef PS2_FUNCTION_LOG_TRACKER
#include "ps2_log.h"
#endif
"""

# Shared by the overrides and the conformance test functions (unity builds: guarded).
FIX_DEFS = r"""
#ifndef SDBZ_SQRT_FIXES_DEFINED
#define SDBZ_SQRT_FIXES_DEFINED 1
#define SDBZ_FPU_SQRT_ABS_S(a) Ps2FpuSqrtS(std::fabs((float)(a)))
static inline float SdbzVuSqrtQ(float ft)
{
    return sqrtf(std::fabs(ft));
}
static inline float SdbzVuRsqrtQ(float fs, float ft)
{
    if (ft == 0.0f)
    {
        uint32_t s, t;
        std::memcpy(&s, &fs, 4);
        std::memcpy(&t, &ft, 4);
        const uint32_t neg = (s ^ t) & 0x80000000u;
        const uint32_t q = (fs != 0.0f) ? (neg | 0x7F7FFFFFu) : neg;
        float r;
        std::memcpy(&r, &q, 4);
        return r;
    }
    return fs / sqrtf(std::fabs(ft));
}
#endif
"""

WORD_RE = re.compile(r"^\s*// 0x[0-9a-f]+: 0x([0-9a-f]+)\s", re.I)
VSQRT_EXPR = "ctx->vu0_q = sqrtf(std::max(0.0f, ft));"
VRSQRT_EXPR = "ctx->vu0_q = (ft > 0.0f) ? (1.0f / sqrtf(ft)) : 0.0f;"
NEEDLES = ("FPU_SQRT_S(", VSQRT_EXPR, VRSQRT_EXPR)


def fix_source(src):
    """Rewrite every sqrt.s / vsqrt / vrsqrt translation; returns (src, {kind: count}).
    A VU expression must follow the comment line of a word that decodes to that op."""
    n = {"sqrt.s": src.count("FPU_SQRT_S("), "vsqrt": 0, "vrsqrt": 0}
    src = src.replace("FPU_SQRT_S(", "SDBZ_FPU_SQRT_ABS_S(")
    out, word = [], None
    for line in src.split("\n"):
        m = WORD_RE.match(line)
        if m:
            word = int(m.group(1), 16)
        for expr, kind, funct in ((VSQRT_EXPR, "vsqrt", 0x3BD), (VRSQRT_EXPR, "vrsqrt", 0x3BE)):
            if expr not in line:
                continue
            if word is None or (word >> 25) != 0x25 or (word & 0x7FF) != funct:
                raise ValueError(f"{kind} expression after word {word!r}, which is not a {kind}")
            if kind == "vsqrt":
                line = line.replace(expr, "ctx->vu0_q = SdbzVuSqrtQ(ft);")
            else:
                fs, fsf = (word >> 11) & 31, (word >> 21) & 3
                fsx = f"_mm_cvtss_f32(_mm_shuffle_ps(ctx->vu0_vf[{fs}], ctx->vu0_vf[{fs}], _MM_SHUFFLE(0,0,0,{fsf})))"
                line = line.replace(expr, f"ctx->vu0_q = SdbzVuRsqrtQ({fsx}, ft);")
            n[kind] += 1
            word = None
        out.append(line)
    return "\n".join(out), n

FUNC_RE = re.compile(r"^// Function: (\S+)\n// Address: 0x([0-9a-f]+) - 0x([0-9a-f]+)\n", re.M)
SIG_RE = re.compile(r"^void (\w+)\(uint8_t\* rdram, R5900Context\* ctx, PS2Runtime \*runtime\) \{", re.M)


def collect():
    fns, problems = [], []
    for p in sorted(OUTPUT.glob("*.cpp")):
        src = p.read_text(errors="replace")
        if not any(k in src for k in NEEDLES):
            continue
        heads, sigs = FUNC_RE.findall(src), SIG_RE.findall(src)
        if len(heads) != 1 or len(sigs) != 1:
            problems.append(f"{p.name}: {len(heads)} function headers / {len(sigs)} signatures (expected 1)")
            continue
        runner = RUNNER / p.name
        if not runner.exists() or runner.read_bytes() != p.read_bytes():
            problems.append(f"{p.name}: runner copy differs from output/ (build syncs output -> runner; rebuild first)")
            continue
        name = sigs[0]
        start, end = int(heads[0][1], 16), int(heads[0][2], 16)
        body = src[src.index("// Function: "):]
        if len(re.findall(rf"\b{re.escape(name)}\b", body)) != 2:   # signature + PS_LOG_ENTRY only
            problems.append(f"{p.name}: {name} referenced inside its own body")
            continue
        body = re.sub(rf"\b{re.escape(name)}\b", PREFIX + name, body)
        try:
            body, n = fix_source(body)
        except ValueError as e:
            problems.append(f"{p.name}: {e}")
            continue
        fns.append({"name": name, "label": heads[0][0], "start": start, "end": end, "body": body, "sites": n, "file": p.name})
    return fns, problems


def collisions(fns):
    """Addresses registered elsewhere (game_overrides / recovered table) or other map entries inside a range."""
    hexes = set()
    for f in (OVERRIDES, RECOVERED_H):
        hexes.update(int(h, 16) for h in re.findall(r"0x00([0-9A-Fa-f]{6})u", f.read_text(errors="replace")))
    starts = set()
    with open(FUNC_MAP, newline="") as fh:
        for row in csv.DictReader(fh):
            starts.add(int(row["start"], 16))
    own = {f["start"] for f in fns}
    out = []
    for f in fns:
        for a in sorted(hexes):
            if f["start"] <= a < f["end"] and a not in own:
                out.append(f"{f['name']}: 0x{a:06x} inside its range is named in game_overrides/recovered")
        for a in sorted(starts):
            if f["start"] < a < f["end"]:
                out.append(f"{f['name']}: func-map entry 0x{a:06x} starts inside its range")
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    fns, problems = collect()
    coll = collisions(fns)
    tot = {k: sum(f["sites"][k] for f in fns) for k in ("sqrt.s", "vsqrt", "vrsqrt")}
    print(f"{len(fns)} functions; sites: " + ", ".join(f"{k} {v}" for k, v in tot.items()))
    for p in problems + coll:
        print("  PROBLEM:", p)
    # the three 10-04 hand copies must come out identical
    old = (FIXDIR / "sqrt_abs_overrides.cpp")
    if old.exists() and "GENERATED by" not in old.read_text(errors="replace")[:200]:
        old_src = old.read_text(errors="replace")
        for f in fns:
            if f"void {PREFIX}{f['name']}(" in old_src:
                seg = old_src[old_src.index(f"// Function: {f['label']}\n"):]
                nxt = seg.find("// Function: ", 10)
                seg = seg if nxt < 0 else seg[:nxt]
                same = seg.strip() == f["body"].strip()
                print(f"  10-04 copy {f['name']}: {'IDENTICAL' if same else 'DIFFERS'}")
                if not same:
                    problems.append(f"{f['name']}: differs from the 10-04 hand copy")
    if problems or coll:
        sys.exit("not writing: fix the problems above")
    if a.check:
        return
    chunks, cur, size = [], [], 0
    for f in fns:
        cur.append(f)
        size += len(f["body"])
        if size > CHUNK_BYTES:
            chunks.append(cur)
            cur, size = [], 0
    if cur:
        chunks.append(cur)
    for old in FIXDIR.glob("sqrt_abs_overrides*.cpp"):
        old.unlink()
    for i, ch in enumerate(chunks):
        name = "sqrt_abs_overrides.cpp" if i == 0 else f"sqrt_abs_overrides_{i + 1}.cpp"
        (FIXDIR / name).write_text(HEADER + FIX_DEFS + "".join("\n" + f["body"] for f in ch), encoding="utf-8")
    table = ["// GENERATED by build_scripts/conformance/gen_sqrt_abs_overrides.py -- do not edit.",
             "// SDBZ_SQRT_ABS_FN(name, start, end): body in sqrt_abs_overrides*.cpp, prefixed " + PREFIX]
    table += [f"SDBZ_SQRT_ABS_FN({PREFIX}{f['name']}, 0x{f['start']:08X}u, 0x{f['end']:08X}u)" for f in fns]
    (FIXDIR / "sqrt_abs_overrides_table.inc").write_text("\n".join(table) + "\n", encoding="utf-8")
    print(f"wrote {len(chunks)} file(s) + sqrt_abs_overrides_table.inc in {FIXDIR}")


if __name__ == "__main__":
    main()
