"""Generate build_scripts/sweeps/fighters.txt: one block per fighter id (Original mode, 2 fights each)."""
import sys

# Priority = disc pictures still unreached per ply/pNN folder (audit_disc_textures.py --coverage gsdump/* --needs, 10-05).
IDS = [11, 9, 22, 2, 23, 28, 27, 26, 12, 4]

HEAD = """# fighters.txt - walk-away FIGHTER sweep (GENERATED by gen_fighters.py; edit the generator, not this file).
# Run:  .\\build_scripts\\gfx_tour.ps1 -Name fighters1 -Script build_scripts\\sweeps\\fighters.txt -Seconds 5400 -Every 60
# Why: `audit_disc_textures.py --coverage gsdump/* --needs` (10-05) = ply/pNN folders never or barely rendered:
#   p11 0/80, p09 8/64, p22 8/64, p02 18/108, p23 20/64, p28 38/120, p27 38/96, p26 18/48, p12 98/200, p04 50/104.
#   H: fighter folder number = the `p1` byte id (VERIFIED only for p01 Goku and p04 Krillin). unlock1 saw the
#   select cursor on ids 1-5, 9-12, 22-30, but never fought them.
# Per fighter (all pieces VERIFIED in earlier runs, the combination is UNRUN):
#   menu -> Original -> select -> column search for p1=N (krillin.txt) -> X into the first fight ->
#   one-hit P2 poke ([0x5B14C0]+12, orig2) until the fight ends -> X through result/world map into fight 2
#   -> mash WITHOUT the poke (specials = eff/ folders) -> pause quit (S D D D X U X, discover2 q0) -> menu.
# Options: Easy, damage 8, 1 round, 45 s (original.txt). Unlock flags poked at boot (unlock1).
# If a fighter id is not in the grid the search ends on whichever fighter is under the cursor; the
# `[scene] ... p1=` lines say which one was really played.

wait app=CAppWarning timeout=900
press X hold=10 gap=50 until app!=CAppWarning timeout=3000
label boot
press S hold=10 gap=50 until app=CAppMenuMain timeout=1500
goto boot 6 if app!=CAppMenuMain
poke 0x5E6B30 0xFFF0 w=4
poke 0x5EC2F0 0x7FE w=4
poke 0x5C7940 1
poke 0x5C7941 8
poke 0x5C7942 0
poke 0x5C7943 0
log fighters sweep: unlock + easy dmg8 1rd 45s
wait ticks=120
"""

BLOCK = """
# ---------------- fighter {n} (ply/p{n:02d}) ----------------
wait app=CAppMenuMain timeout=3000
wait ticks=90
repeat 4
  press U hold=6 gap=6
  press L hold=6 gap=6
end
press X hold=10 gap=50 until app=CAppSelectMain timeout=1200
wait ticks=200
label col{n}
press D hold=6 gap=30 until p1={n} timeout=260
goto picked{n} if p1={n}
press R hold=6 gap=30
goto col{n} 8
label picked{n}
log fighter {n}: cursor on p1={n}?
wait ticks=30
press X hold=10 gap=120 until app=CAppFightMain timeout=3000

# fight 1: mash + one-hit kill
label f1_{n}
repeat 2
  press R hold=12 gap=2
  press Q hold=4 gap=6
  press Q hold=4 gap=6
  press T hold=4 gap=6
  press Q hold=4 gap=6
  press T hold=4 gap=6
end
goto np{n} if app!=CAppFightMain
poke [0x5B14C0]+12 1 w=4
label np{n}
press X hold=6 gap=20
goto f1_{n} 300 if app=CAppFightMain

# result screens / world map -> fight 2
press X hold=10 gap=120 until app=CAppFightMain timeout=3000
log fighter {n}: fight 2 (no poke)

# fight 2: long mash, all attack types, then quit
label f2_{n}
repeat 3
  press R hold=12 gap=2
  press Q hold=4 gap=6
  press Q hold=4 gap=6
  press T hold=4 gap=6
  press X hold=4 gap=6
  press Q+T hold=4 gap=6
  press L hold=12 gap=2
end
goto f2_{n} 25 if app=CAppFightMain

label q{n}
press S hold=10 gap=90
press D hold=6 gap=20
press D hold=6 gap=20
press D hold=6 gap=20
press X hold=10 gap=90
press U hold=6 gap=30
press X hold=10 gap=300
wait app=CAppMenuMain timeout=600
goto q{n} 4 if app!=CAppMenuMain
"""

TAIL = """
log fighters sweep done
wait ticks=300
"""

out = HEAD + "".join(BLOCK.format(n=n) for n in IDS) + TAIL
path = sys.argv[1]
with open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write(out)
print(path, out.count("\n"), "lines")
