"""Generate build_scripts/sweeps/vsall2.txt: N unrolled Versus loops, each with its own R counts + fuzz seeds.
vsall (looped) showed the P1 cursor resets to Goku (p1=0x01) at every select screen, so one R per loop
repeats the same pair; here loop i presses R a_i / b_i / s_i times."""
import sys

N = int(sys.argv[1]) if len(sys.argv) > 1 else 16
START = int(sys.argv[2]) if len(sys.argv) > 2 else 0
OUT = sys.argv[3] if len(sys.argv) > 3 else 'vsall2'
src = open(r'F:\SDBZ Recomp\build_scripts\sweeps\versus2.txt', encoding='utf-8').read().split('\n')
i0 = next(k for k, l in enumerate(src) if l.startswith('wait app=CAppWarning'))
j0 = next(k for k, l in enumerate(src) if l == 'log in Versus char select')
pre = src[i0:j0 + 1]

hdr = r'''# vsall2.txt - GENERATED by scratchpad gen_vsall2.py (N=%d unrolled loops). Versus: loop i presses R a/b/s times
# for P1 / P2 / stage (the P1 cursor RESETS to Goku on every select screen - vsall 10-07 showed p1=0x01 each
# time - so counts are absolute), health frozen while both pads mash a seeded fuzz (H: random chords ->
# specials/supers), then released so the fight ends; result menu D X -> select screen.
# 10-07 vsall2 run 1: a fight is multi-round (2 WINS seen) and outlasted a 2500-tick wait; now P2 hp frozen at 1 after the fuzz
# (rounds end fast) and the result menu gets 25 D X tries.
# VERIFIED vsall loop 1: select -> fight -> fuzz -> fight ends -> result menu -> select again (~5600 ticks/loop).
# Run:  $env:PS2X_PAD2='1'
#       .\build_scripts\gfx_tour.ps1 -Name vsall2 -Script build_scripts\sweeps\vsall2.txt -Seconds 3700 -Every 90
''' % N

def rep(n, line):
    if n <= 0:
        return []
    return ['repeat %d' % n, '  ' + line, 'end']

body = []
for i in range(START, N):
    a = (i * 1) % 13
    b = (i * 3 + 1) % 13
    s = (i * 3) % 17 + 1
    body += [
        '',
        '# ---- loop %d: P1 R x%d, P2 R x%d, stage R x%d' % (i, a, b, s),
        'label charsel%d' % i,
        'wait ticks=150',
    ]
    body += rep(a, 'press R hold=6 gap=24')
    body += [
        'press X hold=10 gap=60',
        'log loop %d P1 confirmed' % i,
    ]
    body += rep(b, 'press R hold=6 gap=24 pad=2')
    body += [
        'press X hold=10 gap=90 pad=2',
        'log loop %d P2 confirmed' % i,
        'wait ticks=120',
        'press X hold=10 gap=120',
        'wait ticks=100',
    ]
    body += rep(s, 'press R hold=6 gap=40')
    body += [
        'press X hold=10 gap=60',
        'press X hold=10 gap=60 pad=2 until app=CAppFightMain timeout=900',
        'log loop %d fight start' % i,
        'wait ticks=300',
        'freeze [0x5AF7F0]+12 250 w=4',
        'freeze [0x5B14C0]+12 250 w=4',
        'fuzz ticks=600 seed=%d max=2 hold=2-8 gap=2-8' % (100 + 3 * i),
        'fuzz ticks=500 seed=%d max=2 hold=2-8 gap=2-8 pad=2' % (101 + 3 * i),
        'unfreeze',
        'freeze [0x5AF7F0]+12 250 w=4',
        'freeze [0x5B14C0]+12 0 w=4',
        'fuzz ticks=1500 seed=%d max=2 hold=2-8 gap=2-8 until app!=CAppFightMain' % (102 + 3 * i),
        'unfreeze',
        'log loop %d left fight' % i,
        'label result%d' % i,
        'wait ticks=200',
        'goto menu%d if app=CAppMenuMain' % i,
        ('goto charsel%d if app=CAppSelectMain' % (i + 1)) if i + 1 < N else 'goto done if app=CAppSelectMain',
        'press D hold=6 gap=30',
        'press X hold=10 gap=200',
    ]
    nxt = ('goto charsel%d if app=CAppSelectMain' % (i + 1)) if i + 1 < N else 'goto done if app=CAppSelectMain'
    body += [
        nxt,
        'goto menu%d if app=CAppMenuMain' % i,
        'goto result%d 25' % i,
        'log stuck after result - pause routine',
        'press S hold=10 gap=90',
        'press U hold=6 gap=30',
        'press X hold=10 gap=300',
        'goto menu%d' % i,
        '',
        '# main menu -> Versus select, then the next loop',
        'label menu%d' % i,
        'wait app=CAppMenuMain timeout=3000',
        'wait ticks=90',
        'repeat 4',
        '  press U hold=6 gap=6',
        '  press L hold=6 gap=6',
        'end',
        'press D hold=6 gap=30',
        'press R hold=6 gap=30',
        'log loop %d menu path D R (expect mode=3)' % i,
        'press X hold=10 gap=60 until app=CAppSelectMain timeout=600',
        'goto vs_ok%d if mode=3' % i,
        'log NOT VERSUS - backing out',
        'press T hold=10 gap=60 until app=CAppMenuMain timeout=300',
        'press S hold=10 gap=60 pad=2',
        'goto menu%d 2' % i,
        'label vs_ok%d' % i,
        ('goto charsel%d' % (i + 1)) if i + 1 < N else 'goto done',
    ]
body += ['', 'label done', 'log vsall2 finished all loops', 'wait ticks=200']
open('F:\\SDBZ Recomp\\build_scripts\\sweeps\\' + OUT + '.txt', 'w', encoding='utf-8', newline='\n').write(
    '\n'.join(hdr.split('\n') + pre + body) + '\n')
print('ok', N)
