# BuildInfo.cmake
# Runs at build time (not configure time) to write build_info.h with
# git commit count and short hash. Called via add_custom_command.
#
# Restored 2026-07-14 from commit edfe0e16 for the RecompDebugger revival
# (dropped from the tree along with the rest of the debugger scaffolding
# when the repo was flattened).

find_package(Git QUIET)

set(BUILD_NUMBER "0")
set(BUILD_HASH "unknown")

if(GIT_FOUND)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-list --count HEAD
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE BUILD_NUMBER
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE BUILD_HASH
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
endif()

if(NOT BUILD_NUMBER OR BUILD_NUMBER STREQUAL "")
    set(BUILD_NUMBER "0")
endif()
if(NOT BUILD_NUMBER_OFFSET OR BUILD_NUMBER_OFFSET STREQUAL "")
    set(BUILD_NUMBER_OFFSET "0")
endif()
math(EXPR BUILD_NUMBER "${BUILD_NUMBER} + ${BUILD_NUMBER_OFFSET}")
if(NOT BUILD_HASH OR BUILD_HASH STREQUAL "")
    set(BUILD_HASH "unknown")
endif()

file(WRITE "${OUTPUT_FILE}"
"#pragma once
// Auto-generated by CMake at build time — do not edit
#define BUILD_NUMBER ${BUILD_NUMBER}
#define BUILD_HASH   \"${BUILD_HASH}\"
#define BUILD_DATE   \"${BUILD_DATE}\"
#define BUILD_STRING \"Build ${BUILD_NUMBER}-${BUILD_HASH} (${BUILD_DATE})\"
")

message(STATUS "BuildInfo: Build ${BUILD_NUMBER}-${BUILD_HASH} (${BUILD_DATE})")
