"""Populate ps2xRuntime/src/lib/Kernel/recovered/ and regenerate its header.

Two jobs, in order:

  --copy <regen_dir> <baseline_dir>
      Copy in every body the patched regeneration produced that the baseline
      regeneration did not -- i.e. exactly the bodies the recovered func-map
      rows added -- SKIPPING any address already claimed by a hand-written
      override. A working override must keep its address; re-registering over
      it would silently replace a proven fix with a machine translation.

  (always)
      Rewrite recovered_functions.h from whatever .cpp files are in the folder:
      one declaration per body, plus the kRecoveredFns address->body table that
      game_overrides.cpp loops over.

WHY A TABLE AND NOT 135 registerFunction LINES
----------------------------------------------
game_overrides.cpp is scanned by build.ps1 to build fn_forward_decls.h, and
that header is included by every runner TU. The scan looks for
`void fn_..._0x...(uint8_t *rdram` DEFINITIONS, so calls are safe -- but the
fewer edits that file needs, the smaller the chance of tripping it later.
Adding a body becomes: drop the .cpp in, re-run this script.

⚠ Do NOT run ps2_recomp with the live config.toml to produce these. That writes
into output/, which build.ps1 syncs into src/runner/, which changes
fn_forward_decls.h and triggers a 30+ hour full rebuild. Regenerate to a
scratch directory and copy from there -- which is what --copy does.

RUN
---
    python build_scripts/funcmap/gen_recovered_header.py \
        --copy <scratch>/regen <scratch>/regen_base
"""
import argparse
import glob
import os
import re
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
DEST = os.path.join(ROOT, "ps2xRuntime", "src", "lib", "Kernel", "recovered")
OVERRIDES = os.path.join(ROOT, "ps2xRuntime", "src", "lib", "game_overrides.cpp")
HEADER = os.path.join(DEST, "recovered_functions.h")

ADDR_RE = re.compile(r"_0x([0-9a-fA-F]+)\.cpp$")
SYM_RE = re.compile(r"^void\s+(\w+)\s*\(uint8_t\s*\*\s*rdram", re.M)

BANNER = '''#pragma once
//
// Declarations for the function bodies recovered in ps2xRuntime/src/lib/Kernel/recovered/.
//
// WHY THESE EXIST
// ---------------
// export_func_map.py built sdbz_func_map_merged.csv by walking idautils.Functions()
// and writing f.start_ea/f.end_ea. In IDA's model a function is a set of CHUNKS, and
// those two fields describe only the ENTRY chunk -- every tail chunk was silently
// dropped from the map. The recompiler emits one body per map row, so the dropped
// ranges got no body, and a direct `j` into one dispatched to nothing. That is the
// "missing-body" dispatch-hole class.
//
// The map now carries those ranges (build_scripts/funcmap/recover_hole_boundaries.py),
// and these are the bodies the production recompiler emitted for them -- machine
// translation, not hand-decoded MIPS.
//
// WHY THEY LIVE HERE AND NOT IN runner/
// -------------------------------------
// build.ps1 regenerates fn_forward_decls.h from a scan of the runner directory, and
// that header is included by all ~4,520 runner TUs. Adding files to runner/ would
// rewrite it and trigger a 30+ hour full rebuild. ps2xRuntime/CMakeLists.txt already
// does GLOB_RECURSE over src/lib/Kernel/*.cpp with CONFIGURE_DEPENDS, so this
// subfolder is picked up with no CMakeLists edit and no runner rebuild.
//
// This header is included ONLY by game_overrides.cpp, which registers these bodies.
// Do not include it from a widely-included header.
//
// GENERATED by build_scripts/funcmap/gen_recovered_header.py -- do not hand-edit.

#include <cstdint>

struct R5900Context;
class PS2Runtime;

'''


def claimed_addresses():
    """Addresses a hand-written override already owns -- register OR replace."""
    txt = open(OVERRIDES, errors="ignore").read()
    out = set()
    for pat in (r"registerFunction\s*\(\s*0x([0-9A-Fa-f]+)",
                r"replaceFunction\s*\(\s*0x([0-9A-Fa-f]+)"):
        out |= {int(m.group(1), 16) for m in re.finditer(pat, txt)}
    return out


def copy_new(regen, baseline):
    base = {os.path.basename(p) for p in glob.glob(os.path.join(baseline, "**", "*.cpp"),
                                                   recursive=True)}
    claimed = claimed_addresses()
    os.makedirs(DEST, exist_ok=True)
    copied = skipped = 0
    for p in sorted(glob.glob(os.path.join(regen, "**", "*.cpp"), recursive=True)):
        name = os.path.basename(p)
        if name in base:
            continue  # not new -- baseline already had it
        m = ADDR_RE.search(name)
        if not m:
            continue
        if int(m.group(1), 16) in claimed:
            skipped += 1
            continue
        shutil.copy2(p, os.path.join(DEST, name))
        copied += 1
    print(f"copied {copied} bodies into {DEST}")
    print(f"skipped {skipped} already owned by a hand-written override")


def gen_header():
    entries = []
    for p in sorted(glob.glob(os.path.join(DEST, "*.cpp"))):
        m = ADDR_RE.search(os.path.basename(p))
        sym = SYM_RE.search(open(p, errors="ignore").read())
        if not (m and sym):
            print(f"  WARN: no address/symbol in {os.path.basename(p)}, skipped")
            continue
        entries.append((int(m.group(1), 16), sym.group(1)))
    entries.sort()

    lines = [BANNER]
    for addr, sym in entries:
        lines.append(f"void {sym}(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime);\n")
    lines.append("""
// Guest address -> recovered body. Addresses already claimed by a hand-written
// override (registerFunction or replaceFunction in game_overrides.cpp) are
// deliberately absent: the working override must keep the address.
struct RecoveredFn
{
    uint32_t addr;
    void (*fn)(uint8_t *, R5900Context *, PS2Runtime *);
};

inline constexpr RecoveredFn kRecoveredFns[] = {
""")
    for addr, sym in entries:
        lines.append(f"    {{0x{addr:08X}u, &{sym}}},\n")
    lines.append("};\n")

    with open(HEADER, "w", newline="\n") as fh:
        fh.write("".join(lines))
    print(f"wrote {HEADER}: {len(entries)} bodies")
    return len(entries)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--copy", nargs=2, metavar=("REGEN", "BASELINE"),
                    help="copy newly-generated bodies in before regenerating the header")
    args = ap.parse_args()
    if args.copy:
        copy_new(args.copy[0], args.copy[1])
    gen_header()


if __name__ == "__main__":
    main()
